### ISSUE TITLE
Is that the development is stopped ?

### ISSUE THREAD

**Issue by Galixte** [marcovo/phpbb_hidebbcode#29]
Hi @marcovo,

no news about dev of your extension ?

**Comment by marcovo** [comment]
Hi @Galixte ,

I find that I actually have too little interest in this extension to continue development. Although I'd like to continue developing it, other things have my priority now.

Anyone wanting to taking it over (same holds for MathJax extension) is free to do so; I wonder if there is any export function for issues, etc.. in github?

Regards,
Marco

**Comment by Galixte** [comment]
I don’t know, thanks for information !
